# Generated by Django 5.0.7 on 2024-07-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_campeonato', models.CharField(choices=[('LIGA', 'Liga'), ('MUERTE_SUBITA', 'Muerte Súbita'), ('FASE_GRUPOS', 'Fase de Grupos')], max_length=20)),
                ('deporte', models.CharField(max_length=50)),
                ('nro_equipos', models.IntegerField()),
                ('nro_jugadores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField(unique=True)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.IntegerField()),
                ('anotaciones', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasIndividuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.IntegerField()),
                ('anotaciones', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('equipos', models.ManyToManyField(to='campeonato.estadisticaequipo')),
                ('deportistas', models.ManyToManyField(to='campeonato.estadisticasindividuales')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.equipo')),
                ('jugadores', models.ManyToManyField(to='campeonato.deportista')),
            ],
            options={
                'unique_together': {('equipo', 'campeonato')},
            },
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='campeonato.Inscripcion', to='campeonato.equipo'),
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacion_equipo1', models.IntegerField()),
                ('anotacion_equipo2', models.IntegerField()),
                ('equipo_ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganador', to='campeonato.equipo')),
                ('equipo_perdedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdedor', to='campeonato.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_partido', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='campeonato.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='campeonato.equipo')),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campeonato.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('posiciones', models.ManyToManyField(to='campeonato.posicion')),
            ],
        ),
    ]
