# Generated by Django 5.0.7 on 2024-08-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='empate',
            field=models.BooleanField(default=False),
        ),
    ]
