# Generated by Django 5.0.7 on 2024-07-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='inicializado',
            field=models.BooleanField(default=False),
        ),
    ]
