# Generated by Django 5.0.7 on 2024-08-03 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto')], max_length=20)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=20)),
                ('tipo', models.CharField(choices=[('liga', 'Liga'), ('eliminatoria', 'Eliminatoria'), ('grupos', 'Grupos')], max_length=20)),
                ('nro_equipos', models.PositiveIntegerField()),
                ('nro_deportistas', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('inicializado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto')], max_length=20)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('deportistas', models.ManyToManyField(blank=True, related_name='participaciones', to='campeonato.deportista')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.equipo')),
            ],
            options={
                'unique_together': {('equipo', 'campeonato')},
            },
        ),
        migrations.AddField(
            model_name='deportista',
            name='participacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deportistas_participacion', to='campeonato.participacion'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(blank=True, through='campeonato.Participacion', to='campeonato.equipo'),
        ),
    ]
