# Generated by Django 5.0.7 on 2024-08-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='campeonato.campeonato'),
        ),
    ]
